exclude: [node_modules, gulpfile.js, yarn.lock, package.json]

# Dependencies
markdown: kramdown

# Permalinks
permalink: /:title.html

# Setup
title: Cook it up!
tagline: 'A food blog'
description: >
  A fun cooking blog that's gonna stir up some grumbling in that good ol' tum of you.
url: 'justenrickert.github.io/cookitup'
baseurl: /cookitup/

author:
  name: 'Justen Rickert'
  url: 'justenrickert.github.io'

paginate: 5

# Custom vars
# version:          2.1.0

github:
  repo: 'https://github.com/JustenRickert/cookitup.github.io'

gem:
  - jekyll-paginate
